divviup/divviup-ts

- package-lock.json
- package.json
- src/benchmarks.ts
> add benchmark suite

- src/dap/ciphertext.ts
- src/dap/client.ts
- src/dap/encoding.ts
- src/dap/report.ts
From @BranLwyd's review feedback
> {encodeArray, encodeOpaque}16

- src/dap/client.spec.ts
- src/dap/client.ts
> DAPClient fetches HpkeConfigs in generateReport

- src/dap/client.spec.ts
- src/dap/client.ts
[§4.2.2-12](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.2.2-12)
> add retry logic as specified by DAP§4.2.2-12

- src/prio3/circuits/proof.ts
- src/prio3/gadgets/polyEval.ts
- src/prio3/gadgets/proof.ts
- src/prio3/gadgets/query.ts
- src/prio3/genericFlp.ts
* move from copying data to using getters
* verbose names as much as possible
* eliminate an unused Field passed into the Proof gadget constructor
> Prio3 implementation clarity and consistency pass

- src/dap/client.spec.ts
- src/dap/client.ts
This updates the media types to match draft-ietf-ppm-dap-01.
> Update media types

- packages/field/src/index.spec.ts
- packages/field/src/index.ts
closes #22 
I'm not at all sure that I'm testing this appropriately, so extra eyes on that would be appreciated!
> use interpolateRoots (fft interpolation)

- package-lock.json
- package.json
top-level deps weren't the same as package deps, which resulted in a build error when building from the top level locally but not from within the package. I'm going to look into how we can have CI catch this sort of thing better
> top-level deps weren't the same as package deps

- .github/workflows/docker.yml
This starts up the Docker container and checks that it's usable, via the existing `HEALTHCHECK`.
> Add a CI test that the Docker container can run

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/workflows/docker.yml
- README.md
Once this is merged, I still need to:
> Adopt Divvi Up branch model

- packages/dap/src/client.spec.ts
- packages/dap/src/client.ts
- packages/dap/src/constants.ts
- packages/dap/src/report.spec.ts
- packages/dap/src/report.ts
Adopt the message and request path changes coming to
`draft-ietf-ppm-dap-04`, as seen in [DAP PR #398][1].
[1]: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/398
> Adopt DAP-04 HTTP API

- packages/dap/src/client.spec.ts
- packages/dap/src/constants.ts
- packages/dap/src/report.spec.ts
per https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/424, provisionally
> bump `DAP_VERSION` to "dap-04"

- package-lock.json
- package.json
- packages/common/typedoc.json
- packages/dap/src/index.ts
- packages/dap/typedoc.json
- packages/field/typedoc.json
- packages/prg/typedoc.json
- packages/prio3/typedoc.json
- packages/vdaf/typedoc.json
- tsconfig.json
- typedoc.base.json
- typedoc.json
This is a backport of #278, to fix docs on the release/dap-draft-03 branch.
> Merge TypeScript docs across packages, draft 03 backport

- package-lock.json
- packages/interop-test-client/package.json
- packages/interop-test-client/src/index.spec.ts
- packages/interop-test-client/src/index.ts
This ports #217 to the main branch, now that DAP draft-04 is implemented.
> Add interoperation test against Janus

- .mocharc.json
> use mocha exit mode to prevent c8 hang

- .github/workflows/publish.yml
- README.md
- package-lock.json
- packages/common/package.json
- packages/dap/package.json
- packages/field/package.json
- packages/interop-test-client/package.json
- packages/prg/package.json
- packages/prio3/package.json
- packages/vdaf/package.json
This cherry-picks #425, bumps package versions to 0.2.0, and adds package versions to our version compatibility table.
> Prepare for developing next version

- package.json
this allows for slightly faster test runs
```
main:
$ time npm test
< snip >
52.37 real        25.64 user         2.71 sys
run-tests-together:
$ time npm test
< snip > 
42.83 real        12.00 user         1.45 sys
```
> run all tests from top level

- README.md
[rendered](https://github.com/divviup/divviup-ts/blob/update-readme/README.md)
> an effort at updating the readme tables

- package-lock.json
- package.json
This updates the main branch to TypeScript 5.3, to keep up with other release branches.
> Update to Typescript 5.3

- .github/dependabot.yml
we apparently have only been running dependabot for dap-04 and main
> add dependabot for dap-07 branch

- packages/dap/src/constants.ts
- packages/dap/src/report.spec.ts
- packages/dap/src/task.spec.ts
- packages/interop-test-client/src/index.spec.ts
Stacked on https://github.com/divviup/divviup-ts/pull/783. Supports https://github.com/divviup/divviup-ts/issues/778. Effectively implements DAP-09 support (and fixes the CI!).
> Update AAD strings, update interop container

- README.md
- package-lock.json
- packages/common/package.json
- packages/dap/package.json
- packages/field/package.json
- packages/prio3/package.json
- packages/vdaf/package.json
- packages/xof/package.json
Supports https://github.com/divviup/divviup-ts/issues/778
> Prepare release of DAP-09/VDAF-08

- packages/field/src/PrimeField.spec.ts
> Remove test code.
