divviup/divviup-ts

src/prng.spec.ts

This adds a test of rejection sampling using a crafted test vector, ensuring compatibility with other implementations and filling in a tricky line of code coverage.

Add test of rejection sampling

---

src/dap/client.spec.ts
src/dap/client.ts

this may break testing against current janus

abort if the key config content type does not conform to spec

---

src/common.spec.ts
src/common.ts
src/dap/client.spec.ts
src/field.spec.ts
src/field.ts
src/prio3/circuit.ts
src/prio3/circuits/count.ts
src/prio3/circuits/histogram.ts
src/prio3/circuits/proof.ts
src/prio3/circuits/query.ts
src/prio3/circuits/sum.ts
src/prio3/flp.spec.ts
src/prio3/flp.ts
src/prio3/gadget.ts
src/prio3/gadgets/mul.ts
src/prio3/gadgets/polyEval.ts
src/prio3/gadgets/proof.ts
src/prio3/gadgets/query.ts
src/prio3/genericFlp.spec.ts
src/prio3/genericFlp.ts
src/prio3/index.ts
src/prng.spec.ts
src/prng.ts
src/vdaf.spec.ts

This serves two purposes:
* hides the galois field library implementation from public interfaces, preparing us to potentially switch out the library if needed, either now or at some future point
* eliminates round-tripping short bigint arrays through Vector unnecessarily

remove Vector from all interfaces

---

src/dap/client.ts
src/field.spec.ts
src/prio3/gadgets/polyEval.ts
src/prio3/index.ts

This rolls up a handful of fixes I caught while reviewing the codebase. Most of them are documentation or names, the only substantive change is in the PolyEval gadget. (The polynomial degree of the composition of two polynomials is equal to the product of the degrees of the two polynomials, because the highest degree term will be like so: $y=x^a, z=y^b \implies z=(x^a)^b=x^{ab}$. All that's left is $\pm1$ to convert between degrees and number of polynomial coefficients.)

Miscellaneous cleanups

---

src/dap/client.spec.ts
src/dap/client.ts

The string constants in `ROUTES` get used with `URL`'s constructor, and the leading `/` was causing it to treat these paths as absolute. We want a relative path, as we wish to preserve any path prefix in the base URL.

Fix construction of URLs

---

src/vdaf.ts

This updates the VDAF draft number in the domain separation tag. This is needed for DAP draft-01 compatibility.

Update domain separation tag for VDAF draft 01

---

src/index.ts

I think we may need to export the "dap" module from our main file. While it shows up in our documentation already, I wasn't able to import it, and the compiled .js file did not include a reexport for it.

Export dap module

---

README.md
scripts/benchmarks.ts
scripts/liveTest.ts
src/dap/client.spec.ts
src/dap/client.ts
src/dap/nonce.spec.ts
src/dap/nonce.ts
src/dap/report.spec.ts

This adopts changes to the `Nonce` structure in draft 01 of the DAP spec. The randomness component is doubled to 16 bytes long, and the time component is changed from being the time of report submission to the corresponding batch interval start time.
This closes #63.

Nonce changes for draft-ietf-ppm-dap-01

---

packages/dap/src/client.spec.ts
packages/dap/src/client.ts
packages/dap/src/nonce.ts

closes #97 
Note: I opted to use an object for the additional optional argument to report generation so that if there are future optional options/configs they can be added into that object. At the moment with only one field/property it's a little awkward, but it allows us to add additional arguments as a semver-patch-level change

add an optional argument to specify nonce timestamp in report generation

---

package-lock.json
packages/dap/package.json
packages/field/package.json
packages/prg/package.json
packages/prio3/package.json
packages/vdaf/package.json

This rewrites all local path dependencies to instead use versions.
This fixes `nx graph`, and I suspect this change is also needed prior to publishing.

Replace local path dependencies with versions

---

.github/workflows/ci.yaml
nx.json
package.json
packages/common/package.json
packages/dap/package.json
packages/field/package.json
packages/prg/package.json
packages/prio3/package.json
packages/vdaf/package.json

This tells Nx that test targets depend on the build target, and then adds a `ci` lifecycle task in the top level package.
This has two benefits: `npm test` is now sufficient for local development (rather than running two commands) and we may shave a fraction of a second off by letting build and test tasks pipeline together.

Configure Nx target dependencies, redo `ci` script

---

packages/prio3/src/prio3.ts
packages/vdaf/src/index.spec.ts
packages/vdaf/src/index.ts

Rename PrepareMessage to PrepareState

---

packages/prio3/src/circuits/histogram.ts
packages/prio3/src/circuits/sum.ts

This fixes errors in the circuits for two of the Prio3 VDAFs. They were using the wrong powers of a joint randomness value in random linear combinations. (See https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-01.html#section-7.4.2-7 and https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-01.html#section-7.4.3-5)
Because the client only evaluates the circuit in order to record gadget wire inputs, and because these two circuits did not have any gadgets downstream of the incorrect random linear combinations, this change has no effect on proofs in reports. It does correct errors in test vector output, which includes the circuit's output value on shares, as part of preparation.

Fix histogram and sum circuits

---

packages/dap/src/index.ts

This may help address #89, in that at least now it will be `require("@divviup/dap").DAPClient`

Export named dap client

---

.github/workflows/docker.yml

This adds a GitHub Actions workflow to build the interop test Docker image, and push the image to Docker Hub (when building from the main branch).

Add a CI workflow to build and push Docker image

---

.github/workflows/docker.yml

This grants `id-token` permissions to the Docker action, so that it can use the `google-github-actions/auth@v0` action.

Fix permissions of Docker CI action

---

Dockerfile.interop_client

This rewrites the interop container Dockerfile as a multi-stage build. The first stage installs all necessary build tools, compiles the code, and bundles it. The second stage installs only the runtime dependencies, and copies compiled JS files from the first stage. This results in drastic file size savings -- according to `docker image ls`, the image went from 1.13GB to 180MB. The frequently-changing layers will be smaller still, as `node_modules` is 15.4MB and `packages` is 1.2MB. I checked that the resulting image still functions by running it through [`dap-interop-test-runner`](https://github.com/divergentdave/dap-interop-test-runner).

Shrink Docker image size via multi-stage build

---

.github/workflows/docker.yml

This updates the "Docker" workflow to also push to the new public container image repository. As before, the newly added steps are guarded by a conditional, so that they only run on commits from main.

CI: Push container image to public repository

---

.github/workflows/docker.yml

This tells google-github-auth to not set environment variables (with the GCP project name, token file location, etc.). Since we only use the resulting token via an actions output, we don't need these environment variables. Additionally, this gets rid of some warnings from the second invocation, which reported that previously set environment variables were being overwritten.

Turn off unused env vars from google-github-auth

---

.github/workflows/docker.yml

#134 was not effective, as the default value for `export_environment_variables` was also true. This explicitly sets the input to false.

Really turn off unused environment vars

---

Dockerfile.interop_client

This adds a `HEALTHCHECK` directive to the interop test Dockerfile. The health check command uses busybox to check if the Node process is listening for TCP connections yet. I plan to make use of this with [`testcontainers::core::WaitFor::Healtcheck`](https://docs.rs/testcontainers/latest/testcontainers/core/enum.WaitFor.html#variant.Healthcheck).

Add HEALTHCHECK directive to container

---

packages/vdaf/src/index.spec.ts

reference: [vdaf.sage#L274-L355](https://github.com/cfrg/draft-irtf-cfrg-vdaf/blob/ee2db72/poc/vdaf.sage#L274-L355)
I'm not entirely sure why this changed, but we might as well mirror the changes here

update test vdaf to align with test vdaf in poc

---

.github/workflows/docker.yml

This bumps the Docker container tag to reflect that we now implement DAP-03. This is a follow-up to #175.
Once this lands, I'll go into the registries and manually rewind the `dap-draft-02` tag to the last image that actually supported DAP-02, which is also tagged as `us-west2-docker.pkg.dev/divviup-artifacts-public/divviup-ts/divviup_ts_interop_client:4bc5b78`, with digest `sha256:1fdcbea395465eeac1cb49f8bb65f419d9b5e147a993f8cf912310a8ea0b62e6`.

Update docker image tag

---

packages/dap/src/client.spec.ts

this changes the behavior of the mock, in that it previously returned a 404. that behavior was unused in our tests, and an explicit error is currently preferable
issue identified in #199

improve error when a request is made that has no matching mock

---

.github/CODEOWNERS

`@divviup/committers` wasn't being recognized as a code owner because I put the two entries on separate lines.

Fix CODEOWNERS format

---

package.json

The `docs` workflow has been failing for about 7 months ([1]). We just need the top-level `package.json`'s `docs` command to dispatch to each sub-package's `docs` script.
[1]: https://github.com/divviup/divviup-ts/actions/workflows/docs.yml

Fix `npm run docs`

---

packages/interop-test-client/bin/interop-test-client
packages/interop-test-client/package.json
packages/interop-test-client/src/index.spec.ts
packages/interop-test-client/src/index.ts

This adds an interop test against Janus. It pulls the relevant Janus images, starts them up, alongside an in-process divviup-ts client, and runs aggregations. I'm filing this against the release/dap-draft-03 branch first, because both draft-04 implementations are not ready yet.
As a next step, we could give the tests another mode (likely selected with an environment variable) where they also run a container for the divviup-ts client, so we can test container images after building them.

Janus interop test, DAP draft-03

---

.github/workflows/docker.yml

This switches the Docker workflow from using secrets to variables for names of workload identity providers and service accounts.

Use variables in lieu of secrets, draft 03 branch

---

.github/workflows/docker.yml

This switches the Docker workflow from using secrets to variables for names of workload identity providers and service accounts.

Use variables in lieu of secrets

---

package-lock.json
package.json
packages/common/typedoc.json
packages/dap/src/index.ts
packages/dap/typedoc.json
packages/field/typedoc.json
packages/prg/typedoc.json
packages/prio3/typedoc.json
packages/vdaf/typedoc.json
tsconfig.json
typedoc.base.json
typedoc.json

This updates some configuration files to get typedoc merging documentation across packages. This uses the new "packages" entry point strategy from typedoc version 0.24.
`typedoc` is emitting some warnings, mostly related to item visibility, so I'll get those cleaned up before marking this ready for review.

Merge TypeScript docs across packages

---

.github/workflows/docs.yml

The docs workflow is still failing, this should fix it by building type declarations first.

Run build before generating docs in CI

---

.github/dependabot.yml
README.md

Updates `README.md` and dependabot configuration to indicate that the `release/dap-draft-03` branch is no longer supported and that `main` is now working toward implementing `draft-ietf-ppm-dap-04`.

Drop support for `draft-ietf-ppm-dap-03`

---

.github/dependabot.yml

This adds a Dependabot group for the packages we use from the hpke-js monorepo.

Add Dependabot group for hpke-js

---

README.md
packages/dap/src/index.ts
packages/dap/src/report.ts
packages/dap/src/task.spec.ts
packages/dap/src/task.ts
packages/dap/src/taskId.spec.ts
packages/interop-test-client/src/index.spec.ts
packages/interop-test-client/src/index.ts
scripts/benchmarks.ts
scripts/liveTest.ts

and rename `Task.taskId` to `Task.id`
closes #408

rename DAPClient to Task

---

.github/workflows/publish.yml

This adds a workflow to run `npm publish` on all our (non-private) packages.

Add GitHub Actions workflow to publish to NPM

---

packages/dap/src/hpkeConfig.spec.ts
packages/dap/src/hpkeConfig.ts

This fixes #390. The `HpkeConfig` constructor is changed to allow any wire-format-compatible values, and checking against the known algorithms is deferred until we touch our backend crypto library.

Gracefully handle unrecognized HPKE algorithms

---

.npmignore

This adds two patterns to `.npmignore` to exclude test files and test vectors. I figure we may as well leave these out, since they won't be used. I confirmed that a separate package importing the resulting tarballs runs fine without these files.

Exclude tests and test vectors from packages

---

.eslintrc.json
packages/dap/src/hpkeConfig.spec.ts
packages/interop-test-client/src/index.ts
scripts/benchmarks.ts

This removes a log statement that was making my terminal go :bell:

Remove extra console.log() statement in test

---

.github/dependabot.yml
README.md

Update README to indicate that DAP-04 support is complete and that DAP-07 support is being worked on.
Update dependabot config to manage `release/dap-draft-04`.

Prepare to branch for DAP-04

---

.github/workflows/publish.yml

Scoped package names by default imply restricted package access, which is a paid feature. This will only be needed the first time any package is published.

Create new packages with public access enabled

---

package-lock.json
packages/common/package.json
packages/dap/package.json
packages/field/package.json
packages/interop-test-client/package.json
packages/prio3/package.json
packages/vdaf/package.json
packages/xof/package.json

For review:
The version strategy this PR uses is as follows
* patch-bump packages that have only non-breaking changes (`@divviup/field`, `@divviup/common`)
* update minor versions of rfc-draft-tracking packages to their relevant draft versions, which happen to all be 07 (`@divviup/dap`, `@divviup/vdaf`, `@divviup/prio3`)
* start `@divviup/xof` out at 0.1, as it has no previous releases

bump versions for dap-07 and vdaf-07

---

package-lock.json
packages/dap/package.json
packages/dap/src/browser.ts

closes #407 
when this is published, we will be able to provide standalone examples like this:
```html
<html>
<body>
<script src="https://unpkg.com/@divviup/dap/dist/browser.js"></script>
<script>
new divviup.dap.Task({
type: "count",
id: "...",
leader: "https://xxx.api.divviup.org/",
helper: "https://yyy.api.divviup.org/",
timePrecisionSeconds: 3600
}).sendMeasurement(true);
</script>
</body>
</html>
```

add a single-file browser build

---

.github/workflows/publish.yml

apparently npm doesn't like symlinks (https://github.com/npm/cli/issues/ 6746) so we copy them on publish. eventually we should write full per-package READMEs but this is better than nothing

copy readme into packages before publishing

---

package-lock.json
package.json
packages/field/package.json

there seem to be a number of vulnerabilities in npm-upgrade's dependencies, and it is unclear if this package is maintained. in order to keep the security tab and npm audit clear, this pr removes this dependency.
I retained the npm upgrade-interactive script, which works just fine if you have npm-upgrade installed globally

remove npm-upgrade from dependencies

---

packages/dap/src/task.spec.ts
packages/interop-test-client/src/index.ts

I was trying to specify `time` when using the upload interop test API endpoint, and it didn't work. The issue is that we are missing a conversion from seconds to milliseconds, which `new Date(value)` expects. I also improved a related unit test that made a similar mistake, but got away with it since it was using the epoch time itself.

Interop test container: fix handling of "time"

---

.github/dependabot.yml

Currently, Dependabot is failing to update typedoc and typedoc-plugin-missing-exports. The former has a PR that is failing due to unsatisfied peerDependencies, and the latter is stuck with `update_not_possible`. This adds a Dependabot group covering the two, which should hopefully unstick things. If not, we'll need a manual dependency update PR.

Add Dependabot group of typedoc and related plugin

---

package-lock.json
package.json

I noticed there was a deprecation warning on `@types/expect` when installing packages, because `expect` now provides its own types. Upon further inspection, we don't actually use `expect`. This dependency has been present since the initial commit, but we ended up using other test utilities.

Remove dev-dependency on @types/expect

---

packages/field/src/PrimeField.spec.ts

Providing the type of the 'this' object addresses a no-base-to-string lint that was previously ignored.

Specify signature of toJSON method in tests

---

packages/dap/package.json

The `dap` package lacks ES module support. This change configures explicit import paths for ESM users (preferred by many bundlers like Vite) using the package.json `exports`  field.

Add ESM support to dap via package.json exports

---

package-lock.json
packages/dap/package.json

This bumps the version of the @divviup/dap package, in preparation for a release, to pick up the new `exports` package metadata from #1034.

Bump version of @divviup/dap

---

package-lock.json
packages/common/package.json
packages/common/src/index.ts
packages/field/package.json
packages/field/src/PrimeField.ts
tsconfig.json

The combination of `esnext + node` for TypeScript's module settings is not the recommended approach for modern Node.js projects: see [why-we-need-nodenext-typescript-compiler-option-when-we-have-esnext](https://stackoverflow.com/questions/71463698/why-we-need-nodenext-typescript-compiler-option-when-we-have-esnext) and [typescript reference](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext).
This PR implements two main changes:
1. Updates TypeScript configuration to use `nodenext + nodenext` for both `module` and `moduleResolution`
2. Replaces the outdated `one-webcrypto` dependency (last updated 3+ years ago) with `@storacha/one-webcrypto`, a maintained fork that supports modern module resolution patterns.

Update module and moduleResolution to nodenext
